Initial version of Pool, Event, EffectType and ItemBase scripts
ninito-ph/TeamGeleiaJam pull request #3
Opened 2021-01-19 20:49 UTC by Daniel-Brum

@ninito-ph , I need your guidance. Thanks in advance and sorry for taking so long.

2021-01-19 21:40 UTC, ninito-ph requested changes
Fiz vários comentários nos scripts. A maioria sendo mudanças rápidas. Fora isso, o código está certinho. Gostei da implementação da ObjectPool.

2021-01-19 21:40 UTC, ninito-ph commented on Assets/Scripts/MonoBehavior/EEffectType.cs
> +    "Slowness"
O enum EEffectType existe pra definir os efeitos pra status effects, logo só eles são relevantes de existir aqui. Reduz os EEffectTypes pra

- DamageModifier (Isso vai modificar a porcentagem do dano visando reduzir ou aumentar ela)
- Slow (Reduz a velocidade de movimento)
- Weaken (Reduz a velocidade do carregamento de força do flick)

2021-01-19 21:40 UTC, ninito-ph commented on Assets/Scripts/MonoBehavior/ItemBase.cs
> +    	this.Pool();
Usar this.Pool() nesse contexto é redundante.

2021-01-19 21:40 UTC, ninito-ph commented on Assets/Scripts/MonoBehavior/ItemBase.cs
> +
Brum, adiciona 3 métodos pra ativação dos efeitos por favor:

- OnFlick()
- OnActivate()
- OnHitTarget(HurtController hurtController, StatusEffectController statusEffectController)

2021-01-19 21:40 UTC, ninito-ph commented on Assets/Scripts/MonoBehavior/Singletons/IPoolable.cs
> +    void Pool();
Estas funções devem ser públicas.

2021-01-19 21:40 UTC, ninito-ph commented on Assets/Scripts/MonoBehavior/Singletons/ObjectPool.cs
> +public class ObjectPool : IPoolable
A object pool não é um item poolável, então ela não implementa a interface IPoolable

2021-01-19 21:40 UTC, ninito-ph commented on Assets/Scripts/MonoBehavior/Singletons/ObjectPool.cs
> +    	returnedObject.SetActive(true);
Logo depois de obter o GameObject você deve fazer um GetComponent<IPoolable> nele, e guardar o resultado em uma variável do tipo IPoolable. Isso vai retornar um componente que implementa a interface IPoolable, no caso, o ItemBase.

Logo antes de chamar returnedObject.SetActive(true), você deve chamar IPoolable.EnableObject(), pra resetar todas as variáveis relevantes dele, pra essencialmente fazer parecer que ele é 'novo'.

2021-01-19 21:40 UTC, ninito-ph commented on Assets/Scripts/MonoBehavior/Singletons/ObjectPool.cs
> +    	}
Essa corotina deve rodar permanentemente no seguinte loop

> WaitForSeconds cleanupTimer = new WaitForseconds(cleanupTime); // Fazer um cache do WaitForSeconds faz com que não seja necessário alocar memória nova pra classe WaitForSeconds todo loop.
while (true)
{
    inactiveObjects.RemoveAt(inactiveObjects.Count - 1); // Sem o -1 a lista sempre vai dar OutOfBoundsException
    yield return cleanupTimer; // Isso vai fazer com que a corotina fique em loop eterno removendo os itens de excesso, até que a ObjectPool seja destruída.
}

2021-01-19 21:40 UTC, ninito-ph commented on Assets/Scripts/MonoBehavior/Singletons/ObjectPoolManager.cs
> +    }
Imagino que a dificuldade com esse método seja por causa de não saber qual pool é de qual objeto.

Cria um enum EItemType, e adiciona todos os tipos de item lá. Depois, troca a List<ObjectPool> objectPools por um dicionário Dictionary<EItemType, ObjectPool>; assim, você consegue saber qual pool é de quê pelos pares chave-objeto.

Depois, adiciona três parâmetros pra função RequestObjectFromPool, sendo dos tipo EItemType, Vector3, Quaternion. Dentro da função, vc vai chamar o seguinte:

> objectPools[EItemType].RequestObject(position, rotation);

Assim você consegue contatar a pool do objeto desejado.

2021-01-19 21:53 UTC, Daniel-Brum commented on Assets/Scripts/MonoBehavior/Singletons/ObjectPool.cs
> +    	}
Pergunta meio idiota, mas isso não geraria um problema se de alguma forma a pool ficasse completamente vazia?

2021-01-19 22:59 UTC, ninito-ph requested changes
Só falta alterar a object pool e a interface IPoolable, e a pull request será aceita.

2021-01-19 22:59 UTC, ninito-ph commented on Assets/Scripts/MonoBehavior/Singletons/ObjectPool.cs
> +    	inactiveObjects.Add(instantiatedObject);
Primeiramente, adicione uma variável privada do tipo ObjectPool e um acessor público a interface IPoolable. Depois, injete a dependência assim:
```
GameObject instantiatedObject = Instantiate(inactiveObjects[0]);
instantiatedObject.GetComponent<IPoolable>().ObjectPool = this;
instantiatedObject.SetActive(false);
inactiveObjects.Add(instantiatedObject);
```

2021-01-19 22:59 UTC, ninito-ph commented on Assets/Scripts/MonoBehavior/Singletons/IPoolable.cs
> +    #region Custom Methods
Acima desta linha adicione uma variável privada do tipo ObjectPool, e um acessor público para que ela seja acessada externalmente.

2021-01-20 01:13 UTC, Daniel-Brum commented
Paulo, creio que agora é só o broker e tá tudo certo. Vou ler aqui os comments da #4 enquanto isso.

2021-01-20 01:33 UTC, ninito-ph approved these changes
Pull request aprovada.

2021-01-20 01:33 UTC, merged